name: CI
on:
  push:
    branches:
      - styled
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: |
          npm install
          npm run-script build
          # rm -rf build/404.html
          # cp build/index.html build/404.html
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@3.0.3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: 'build'
